### ISSUE TITLE
res._removedHeader does not exists

### ISSUE THREAD

**Issue by imbolc** [expressjs/compression#91] opened 2016-07-31 14:54 UTC
I got this error:

```
TypeError: Cannot set property 'content-length' of undefined
    at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:388:30)
    at ServerResponse.onResponseHeaders (/home/imbolc/0/p/action-loop/node_modules/compression/index.js:202:13)
    at ServerResponse.writeHead (/home/imbolc/0/p/action-loop/node_modules/on-headers/index.js:46:16)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.write (/home/imbolc/0/p/action-loop/node_modules/compression/index.js:83:14)
    at /home/imbolc/0/p/action-loop/node_modules/express-pouchdb/lib/routes/changes.js:64:17
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

I just fix this with monkey patching of `compression/index.js`:
```
      // header fields                                                                                                        
      res.setHeader('Content-Encoding', method)                                                                               
      try {                                                                                                                   
        res.removeHeader('Content-Length')                                                                                    
      } catch (e) {                                                                                                           
        console.log(e)                                                                                                        
        if (res._removedHeader === undefined) {                                                                               
          res._removedHeader = {};                                                                                            
        }                                                                                                                     
        res.removeHeader('Content-Length')                                                                                    
      } 
```

Do you have any ideas why does it happen and what the right way to fix this?

**Comment by dougwilson** [comment] 2016-08-14 23:34
Hi @imbolc, very weird, I have never seen such an error and our tests have never encountered it, either :/

Would you be able to provide all the following?

1. The version of Node.js you are using.
2. The version of this module you are using.
3. Complete code that has this issue, such that I can copy and paste it into a file and run the server.
4. Provide the steps I need to perform against your code to cause the error to appear.

**Comment by jameswestnz** [comment] 2016-08-17 22:35
@dougwilson I have a feeling this was related to a version of hoodie at the time - sounds like we'll know more soon in the referenced issue.

**Comment by jameswestnz** [comment] 2016-08-17 22:48
@dougwilson I think it's safe to assume it wasn't `expressjs/compression` that was causing the issue, however I'd be keen to hear from @imbolc on this to double check.

**Comment by gr2m** [comment] 2016-08-25 03:40
The problem is most likely with the `hapi-to-express` module:
https://github.com/hoodiehq/hoodie-store-server/blob/master/index.js#L73-L76

`hapress.res._removedHeader` is undefined and that’s the problem, it’s not related to `compression`, it’s just the place where it blows app because of the `res.removeHeader('Content-Length')` call

**Comment by gr2m** [comment] 2016-08-25 03:53
see https://github.com/jakepruitt/hapi-to-express/issues/5

**Comment by gr2m** [comment] 2016-09-13 06:34
this is not a compression issue, sorry for the noise :) 
I resolved the problem that Hoodie had via https://github.com/hoodiehq/hoodie-store-server/pull/60

Thanks for your great work, @dougwilson :wave:

**Comment by dougwilson** [comment] 2016-09-26 02:28
Ah, thanks for the heads-up, @gr2m ! I see that PR was merged as well. It sounds like I can close this issue. Let me know if I should re-open for any reason :)

**Closed by dougwilson** 2016-09-26 02:28 UTC
