### ISSUE TITLE
Can not make compression work with static files

### ISSUE THREAD

**Issue by davoam** [expressjs/compression#42] opened 2015-05-25 21:14 UTC
Please help. Compression does not work. There is no Content-Encoding in responses
```javascript
var express = require('express');
var compression  = require('compression');
var app = express();

app.set('port', (process.env.PORT || 5000));
app.use(compression());
app.use(express.static(__dirname + '/public'));

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'));
});
```

**Comment by dougwilson** [comment] 2015-05-25 21:30
Hi! Your code above works perfectly for me, but since you didn't provide a static file to use, I cannot help much further.

Compression depends on three main things you didn't provide:

1. What are the request headers you are sending to the server?
2. What is the type of the file you are serving?
3. What is the size of the file?

**Comment by davoam** [comment] 2015-05-25 21:35
Thank you for response. Here is curl of request
curl "http://my-server.com.angular.js" -H "Pragma: no-cache" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36" -H "Accept: */*" -H "Referer: http://my-server.com/" -H "Connection: keep-alive" -H "Cache-Control: no-cache" --compressed
And response: 
Accept-Ranges:bytes
Cache-Control:public, max-age=0
Connection:keep-alive
Content-Type:application/javascript
Date:Mon, 25 May 2015 21:32:56 GMT
Etag:W/"e90aa-1077232132"
Last-Modified:Mon, 25 May 2015 21:09:53 GMT
Server:Cowboy
Transfer-Encoding:chunked
Vary:Accept-Encoding
Via:1.1 vegur
X-Powered-By:Express

**Comment by dougwilson** [comment] 2015-05-25 21:39
Thank you. How big is the file (in bytes). By default we will not compress a file if it under 1kb. I can also see by your response you have a proxy between you and the server. This is the problem pretty much 100% of the time. Can you make the request directly to the server without going through the proxy?

**Comment by davoam** [comment] 2015-05-25 21:45
The size of file is 958KB. It does not work even if run node index.js on my computer

**Comment by dougwilson** [comment] 2015-05-25 21:48
Unfortunately everything works perfectly for me with the code you sent. This means that I will just have to await a PR from you that fixes the issue, unfortunately. I will await a PR with the fix :)

**Comment by dougwilson** [comment] 2015-05-25 22:06
I'm going to close this for now due to lack of reproduction. If you are able to figure out the issue and it turns out to be a bug in this module, a PR would be very welcome :) Here is the console session from when I tried to reproduce the issue with the information provided:
```
$ cat app.js
var express = require('express');
var compression  = require('compression');
var app = express();

app.set('port', (process.env.PORT || 5000));
app.use(compression());
app.use(express.static(__dirname + '/public'));

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'));
});

$ node -v
v0.10.33

$ npm i compression express
compression@1.4.4 node_modules\compression
├── vary@1.0.0
├── bytes@1.0.0
├── on-headers@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── compressible@2.0.2 (mime-db@1.10.0)
└── accepts@1.2.7 (negotiator@0.5.3, mime-types@2.0.12)

express@4.12.4 node_modules\express
├── merge-descriptors@1.0.0
├── cookie@0.1.2
├── fresh@0.2.4
├── escape-html@1.0.1
├── utils-merge@1.0.0
├── methods@1.1.1
├── range-parser@1.0.2
├── cookie-signature@1.0.6
├── content-type@1.0.1
├── finalhandler@0.3.6
├── parseurl@1.3.0
├── vary@1.0.0
├── content-disposition@0.5.0
├── serve-static@1.9.3
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── etag@1.6.0 (crc@3.2.1)
├── send@0.12.3 (destroy@1.0.3, ms@0.7.1, mime@1.3.4)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── accepts@1.2.7 (negotiator@0.5.3, mime-types@2.0.12)
└── type-is@1.6.2 (media-typer@0.3.0, mime-types@2.0.12)

$ mkdir public

$ node -pe 'console.log("/* " + new Buffer(958 * 1024) + " */")' > public/example.js

$ ls -lh public/
total 480k
-rw-r--r--    1 user     group     958k May 25 17:59 example.js

$ node app.js &
[1] 14108
Node app is running at localhost:5000

$ curl -XGET -I -H'Accept-Encoding: gzip, deflate, sdch' http://localhost:5000/example.js
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Date: Mon, 25 May 2015 22:03:32 GMT
Cache-Control: public, max-age=0
Last-Modified: Mon, 25 May 2015 21:59:33 GMT
ETag: W/"ef815-3318529146"
Content-Type: application/javascript
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

Please try to follow my console session above yourself to see if it reproduces for you. If following the above still shows `Content-Encoding: gzip` in the response like mine does, then it didn't reproduce the issue. If there are adjustments you can make that reproduce it, please feel free to follow up with the full instructions to reproduce, in the format as above so I can reproduce.

**Closed by dougwilson** 2015-05-25 22:06 UTC
Labels: question

**Comment by davoam** [comment] 2015-05-25 22:07
ok, thank you. I'll try

**Comment by joshmarinacci** [comment] 2015-06-09 22:33
I've had the same problem as well. Your test script worked for me, however. The difference seems to be using -XGET in the curl command. According to this page:
http://stackoverflow.com/questions/8498371/curl-get-and-xget

the difference is that -XGET forces curl to use a GET request. By default it is doing a HEAD request, which I guess doesn't get gzipped.  

So it looks like compression *is* turned on, it just doesn't appear to be thanks to curl.  Could you include instructions for using curl properly to verify gzip in the readme?
